# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_lease_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
