# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_auto_20170623_1728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentalIncome',
            new_name='RentalRate',
        ),
    ]
