# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_auto_20170623_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default='2017-08-01'),
            preserve_default=False,
        ),
    ]
