# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 21:50
from __future__ import unicode_literals

import budgeting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_auto_20170627_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='admin',
            field=models.OneToOneField(on_delete=models.SET(budgeting.models.get_sentinel_user), related_name='lease_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
