# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0004_auto_20170628_1750'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentalrate',
            unique_together=set([('lease', 'budget')]),
        ),
    ]
