# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0005_auto_20170628_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
