# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0006_auto_20170629_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscretionaryAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_date', models.DateField()),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DiscretionaryExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('partialAllowed', models.BooleanField(default=True)),
                ('excessAllowed', models.BooleanField(default=False)),
                ('requestedFunds', models.IntegerField()),
                ('initialFunds', models.IntegerField()),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.DiscretionaryAllocation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscretionaryVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('personal_abs_max', models.IntegerField()),
                ('global_abs_max', models.IntegerField()),
                ('personal_pct_max', models.FloatField()),
                ('global_pct_max', models.FloatField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.DiscretionaryExpense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='discretionaryvote',
            unique_together=set([('user', 'expense')]),
        ),
        migrations.AlterUniqueTogether(
            name='discretionaryexpense',
            unique_together=set([('name', 'allocation')]),
        ),
    ]
