# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0008_auto_20170702_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discretionaryexpense',
            old_name='allocatedFunds',
            new_name='currentAllocatedFunds',
        ),
    ]
