# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0010_auto_20170702_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocationexpense',
            old_name='currentAllocatedFunds',
            new_name='current_allocated_funds',
        ),
        migrations.RenameField(
            model_name='allocationexpense',
            old_name='excessAllowed',
            new_name='excess_allowed',
        ),
        migrations.RenameField(
            model_name='allocationexpense',
            old_name='partialAllowed',
            new_name='partial_allowed',
        ),
        migrations.RenameField(
            model_name='allocationexpense',
            old_name='requestedFunds',
            new_name='requested_funds',
        ),
    ]
