# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0013_auto_20170702_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationexpense',
            name='slug',
            field=models.SlugField(default='badslug'),
            preserve_default=False,
        ),
    ]
