# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0014_allocationexpense_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationexpense',
            name='detail_text',
            field=models.TextField(default='no details provided'),
            preserve_default=False,
        ),
    ]
