# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0016_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='route',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
