# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 00:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0018_auto_20170717_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
