# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0019_auto_20170717_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='show_on_help_page',
            field=models.BooleanField(default=False),
        ),
    ]
