# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0021_user_has_signed_agreements'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationvote',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
