# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0022_allocationvote_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationexpense',
            name='detail_text',
            field=models.TextField(verbose_name='More information about this expense'),
        ),
        migrations.AlterField(
            model_name='allocationexpense',
            name='excess_allowed',
            field=models.BooleanField(default=False, verbose_name='Willing to accept more than the requested amount?'),
        ),
        migrations.AlterField(
            model_name='allocationexpense',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name for this expense'),
        ),
        migrations.AlterField(
            model_name='allocationexpense',
            name='partial_allowed',
            field=models.BooleanField(default=True, verbose_name='Willing to accept less than the requested amount?'),
        ),
        migrations.AlterField(
            model_name='allocationexpense',
            name='requested_funds',
            field=models.IntegerField(verbose_name='How much are you requesting?'),
        ),
        migrations.AlterField(
            model_name='allocationvote',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
