# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0024_auto_20171014_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prompt', models.CharField(max_length=200)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.Election')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
        migrations.AddField(
            model_name='candidate',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='budgeting.Question'),
            preserve_default=False,
        ),
    ]
