# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 15:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0027_question_detail_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='is_live',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 15, 15, 36, 47, 88181, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
