# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0028_auto_20171015_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='detail_text',
        ),
    ]
